image: golang:1.12

stages:
  - test
  - integration

lint:
  stage: test
  script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
    - cd $CI_PROJECT_DIR && golangci-lint run
  allow_failure: true

test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR && make test

integration:
  stage: integration
  image: docker/compose:latest
  services:
    - docker:dind
  script:
    - docker-compose run bricks make integration
