image: golang:1.12

stages:
  - test
  - integration

variables:
  GOPATH: "/tmp/go"

lint:
  stage: test
  script:
    - cd $CI_PROJECT_DIR && make lint
  allow_failure: true

test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR && make test

integration:
  stage: integration
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk update
    - apk add py-pip
    - pip install docker-compose
    - docker-compose run bricks make integration
