image: golang:1.12

stages:
  - test
  - integration

variables:
  GOPATH: "/tmp/go"

lint:
  stage: test
  script:
    - cd $CI_PROJECT_DIR && make lint
  allow_failure: true

test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR && make test

integration:
  stage: integration
  image: docker:latest
  services:
    - docker:dind
  script:
    - wget "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -O /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - /usr/local/bin/docker-compose run bricks make integration
