language: go

before_install:
  - go get github.com/mattn/goveralls

services:
- postgresql
- redis-server

env:
- GO111MODULE=on REDIS_HOSTS=localhost:6379 POSTGRES_HOST=localhost POSTGRES_PASSWORD=

go:
- 1.13.x

after_success:
- GO111MODULE=off go get github.com/mattn/goveralls

script:
  - make ci
  - $GOPATH/bin/goveralls -service=travis-ci
