language: go

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

services:
- postgresql
- redis-server

env:
- GO111MODULE=on REDIS_HOSTS=localhost:6379 POSTGRES_HOST=localhost POSTGRES_PASSWORD=

go:
- 1.13.x

after_success:
- GO111MODULE=off

script:
  - make ci
  - make coveralls-test
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
