language: go

after_success:
- go run ./vendor/github.com/mattn/goveralls -coverprofile=coverage.out -service=travis-ci

services:
- docker

go:
- 1.14.x

script:
- docker-compose run testserver make ci
