version: '3'

services:
  postgres:
    image: postgres:9.5.12
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  pb:
    build: .
    volumes:
      - .:/rails
    ports:
      - "5000:5000"
    environment:
      - RAILS_ENV=development
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SERVICE_NAME=testserver
      - SENTRY_DSN="https://71e5037808ff4acf9e18cd0ab5ee472a:f58b0c9ba48447af953cf377cf1d9b9c@sentry.jamit.de/164"
      - SENTRY_ENVIRONMENT=development
      - SENTRY_RELEASE=`git rev-parse --short HEAD`
      - POSTGRES_USER=testserveruser
      - POSTGRES_DB=testserver
      - POSTGRES_PASSWORD=pace1234!
      - PACE_LIVETEST_INTERVAL=1m
    depends_on:
      - postgres
      - redis
      - jaeger
      - prometheus
