version: '3'

services:
  postgres:
    image: postgres:9.5.12
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    ports:
      # HTTP UI
      - "9000:9000"
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=client
      - MINIO_SECRET_KEY=secret01
      - MINIO_REGION_NAME=us-east-1

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      # HTTP UI
      - "16686:16686"
      # Traces UDP
      - "6831:6831/udp"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    ports:
     - 9090:9090
    volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  testserver:
    image: "golang:latest"
    volumes:
      - .:/srv
    working_dir: /srv
    ports:
      - "3000:3000"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SERVICE_NAME=testserver
      - SENTRY_DSN="https://71e5037808ff4acf9e18cd0ab5ee472a:f58b0c9ba48447af953cf377cf1d9b9c@sentry.jamit.de/164"
      - SENTRY_ENVIRONMENT=development
      - SENTRY_RELEASE=`git rev-parse --short HEAD`
      - PACE_LIVETEST_INTERVAL=10s
      - LOG_FORMAT=console
      - S3_ENDPOINT=minio:9000
      - S3_ACCESS_KEY_ID=client
      - S3_SECRET_ACCESS_KEY=secret01
      - S3_USE_SSL=false
    command: go run -mod=vendor ./tools/testserver
    depends_on:
      - postgres
      - redis
      - minio
      - jaeger
      - prometheus
    restart: always
