name: Golang CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.16' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.node }}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Unit tests
      run: make test
    - name: Integration tests
      run: docker-compose run testserver make ci
  # publish:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.ref == 'refs/heads/master' }}
  #   steps:
  #   - name: Publish coverage
  #     run: go run ./vendor/github.com/mattn/goveralls -coverprofile=coverage.out -service=travis-ci